(define
	(problem grounded-STRIPS-GRIPPER-X-5)
	(:domain grounded-GRIPPER-STRIPS)
	(:init
		
		( AT_BALL1_ROOMA )
		( AT_BALL2_ROOMA )
		( AT_BALL3_ROOMA )
		( AT_BALL4_ROOMA )
		( AT_BALL5_ROOMA )
		( AT_BALL6_ROOMA )
		( AT_BALL7_ROOMA )
		( AT_BALL8_ROOMA )
		( AT_BALL9_ROOMA )
		( AT_BALL10_ROOMA )
		( AT_BALL11_ROOMA )
		( AT_BALL12_ROOMA )
		( FREE_RIGHT )
		( FREE_LEFT )
		( AT-ROBBY_ROOMA )
		
	)
	(:goal
		(and 
		( AT_BALL1_ROOMB )
		( AT_BALL2_ROOMB )
		( AT_BALL3_ROOMB )
		( AT_BALL4_ROOMB )
		( AT_BALL5_ROOMB )
		( AT_BALL6_ROOMB )
		( AT_BALL7_ROOMB )
		( AT_BALL8_ROOMB )
		( AT_BALL9_ROOMB )
		( AT_BALL10_ROOMB )
		( AT_BALL11_ROOMB )
		( AT_BALL12_ROOMB )
		
		)
	)
	

)
